# inherit_from: .rubocop_todo.yml

# Encoding:
#   Enabled: false

# LineLength:
#   Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingBlankLines:
  Enabled: false

# StringLiterals:
#   Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Metrics/LineLength:
  Max: 150

